name: Post release
on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: 'main'
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure git
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"

      # There's a race conditon where a PR could be merged after the tag is created
      # We checkout the latest tag instead of main to prevent accidentally shipping those
      - run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG
          git push origin +HEAD:production
